version: '3.9'

services:
  redis-db:
    extends:
      file: ./services/redis.yml
      service: redis-db

  db-init:
    extends:
      file: ./services/db.yml
      service: db-init

  db:
    depends_on:
      db-init:
        condition: service_completed_successfully
    extends:
      file: ./services/db.yml
      service: db

  backend:
    depends_on:
      db:
        condition: service_healthy
      redis-db:
        condition: service_started
    extends:
      file: ./services/backend.yml
      service: backend
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
      args:
        RELEASE_VERSION: 7.0.2
    links:
      - db:database
    environment:
        ETHEREUM_JSONRPC_HTTP_URL: ${ETHEREUM_JSONRPC_HTTP_URL:-http://localhost:8545}
        ETHEREUM_JSONRPC_TRACE_URL: ${ETHEREUM_JSONRPC_TRACE_URL:-http://localhost:8545}
        CHAIN_ID: ${CHAIN_ID:-'32382'}
        STATS__CONDITIONAL_START__USER_OPS_PAST_INDEXING_FINISHED__ENABLED: false

  # nft_media_handler:
  #   depends_on:
  #     - backend
  #   extends:
  #     file: ./services/nft_media_handler.yml
  #     service: nft_media_handler
  #   build:
  #     context: ..
  #     dockerfile: ./docker/Dockerfile
  #     args:
  #       RELEASE_VERSION: 6.10.0

  visualizer:
    extends:
      file: ./services/visualizer.yml
      service: visualizer

  sig-provider:
    extends:
      file: ./services/sig-provider.yml
      service: sig-provider

  frontend:
    depends_on:
      - backend
    extends:
      file: ./services/frontend.yml
      service: frontend
    environment:
       NEXT_PUBLIC_API_HOST: ${NEXT_PUBLIC_API_HOST:-localhost}
       NEXT_PUBLIC_STATS_API_HOST: ${NEXT_PUBLIC_STATS_API_HOST:-http://localhost:8080}
       NEXT_PUBLIC_API_PROTOCOL: ${NEXT_PUBLIC_API_PROTOCOL:-https}
       NEXT_PUBLIC_APP_PROTOCOL: ${NEXT_PUBLIC_APP_PROTOCOL:-https}
       NEXT_PUBLIC_API_WEBSOCKET_PROTOCOL: ${NEXT_PUBLIC_API_WEBSOCKET_PROTOCOL:-wss}
       NEXT_PUBLIC_APP_HOST: ${NEXT_PUBLIC_APP_HOST:-localhost}
       NEXT_PUBLIC_VISUALIZE_API_HOST: ${NEXT_PUBLIC_VISUALIZE_API_HOST:-http://localhost:8081}
       STATS__CONDITIONAL_START__USER_OPS_PAST_INDEXING_FINISHED__ENABLED: false


  stats-db-init:
    extends:
      file: ./services/stats.yml
      service: stats-db-init

  stats-db:
    depends_on:
      stats-db-init:
        condition: service_completed_successfully
    extends:
      file: ./services/stats.yml
      service: stats-db

  stats:
    depends_on:
      stats-db: 
        condition: service_healthy
      backend: 
        condition: service_healthy
    extends:
      file: ./services/stats.yml
      service: stats
    environment:
      NEXT_PUBLIC_STATS_API_HOST: ${NEXT_PUBLIC_STATS_API_HOST:-http://localhost:8080}
      STATS__CONDITIONAL_START__USER_OPS_PAST_INDEXING_FINISHED__ENABLED: false

  user-ops-indexer:
    depends_on:
      backend:
        condition: service_healthy # Avoid db migration race condition
    extends:
      file: ./services/user-ops-indexer.yml
      service: user-ops-indexer

  proxy:
    depends_on:
      - backend
      - frontend
      - stats
    extends:
      file: ./services/nginx.yml
      service: proxy
